x-database: &db-settings
  image: mysql:8.0
  restart: unless-stopped
  env_file:
    - .env
  environment:
    MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
    MYSQL_DATABASE: ${DB_DATABASE}

x-restart-policy: &restart_policy
  restart: unless-stopped

x-healthcheck-defaults: &healthcheck_defaults
  start_period: 15s
  interval: 10s
  timeout: 10s
  retries: 30

x-kafka: &kafka
  <<: *restart_policy
  depends_on:
    zookeeper:
      condition: service_healthy
  build:
    context: docker/kafka
    dockerfile: kafka.Dockerfile
  environment:
    KAFKA_CLUSTER_ID: 22
    KAFKA_ZOOKEEPER: zookeeper:2181
  ulimits:
    nofile:
      soft: 4096
      hard: 4096
  healthcheck:
    <<: *healthcheck_defaults
    test: [
      "CMD-SHELL",
      "kafka-topics.sh --bootstrap-server localhost:9092 --list --command-config /tmp/command-auth.properties"
    ]

services:
  nginx:
    image: nginx:latest
    container_name: opium-nginx
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - app

  app:
    container_name: opium-app
    build:
      args:
        user: opium-user
        uid: 1000
      context: .
      dockerfile: ./docker/app.Dockerfile
      network: host
    restart: on-failure
    volumes:
      - .:/var/www
    links:
      - db
      - redis

  cron:
    container_name: opium-cron
    build:
      args:
        user: opium-user
        uid: 1000
      context: .
      dockerfile: ./docker/cron.Dockerfile
    restart: on-failure
    volumes:
      - .:/var/www
    links:
      - db
      - redis
      - app

  worker:
    container_name: opium-worker
    build:
      args:
        user: opium-user
        uid: 1000
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: on-failure
    command: bash -c "sleep 3; php artisan horizon"
    healthcheck:
      test: /usr/local/bin/php /var/www/artisan horizon:status || exit 1
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 3
    logging:
      driver: syslog
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - db
      - redis

  redis:
    container_name: opium-redis
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379

  db:
    <<: *db-settings
    container_name: opium-db
    volumes:
      - mysql_data:/var/lib/mysql

  db_branch:
    profiles:
      - local
    <<: *db-settings
    container_name: opium-db-2
    volumes:
      - mysql_data_branch:/var/lib/mysql

  db_testing:
    <<: *db-settings
    container_name: opium-db-testing
    tmpfs:
      - /var/lib/mysql

  phpmyadmin:
    profiles:
      - local
    image: phpmyadmin/phpmyadmin:latest
    container_name: opium-phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: opium-db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 8000M
    ports:
      - "${PHPMYADMIN_PORT}:80"

  adminer:
    profiles:
      - local
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"

  sync:
    container_name: opium-sync
    build:
      args:
        user: opium-user
        uid: 1000
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: on-failure
    command: bash -c "sleep 15; php artisan sync:consume:work"
    healthcheck:
      test: /usr/local/bin/php /var/www/artisan sync:consume:status || exit 1
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 5
    logging:
      driver: syslog
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - db
      - redis

  zookeeper:
    profiles:
      - main
    container_name: opium-zookeeper
    <<: *restart_policy
    build:
      context: docker/kafka
      dockerfile: zookeeper.Dockerfile
    environment:
      ZOOKEEPER_DATA_DIR: /zookeeper/data/zookeeper
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    volumes:
      - kafka_data:/zookeeper/data
    healthcheck:
      <<: *healthcheck_defaults
      test:
        ["CMD-SHELL", 'echo "ruok" | nc -w 2 localhost 2181 | grep imok']

  kafka-1:
    profiles:
      - main
    <<: *kafka
    container_name: opium-kafka-1
    ports:
      - "${KAFKA_1_PORT}:9092"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/tmp/kafka_jaas.conf"
      KAFKA_LOG_DIRS: /kafka/data/kafka-1
      KAFKA_ZOOKEEPER: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: "SASL_PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://:9092"
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
    volumes:
      - kafka_data:/kafka/data
      - ./docker/kafka/command-auth.properties:/tmp/command-auth.properties
      - ./docker/kafka/kafka_jaas.conf:/tmp/kafka_jaas.conf

  kafka-2:
    profiles:
      - main
    <<: *kafka
    container_name: opium-kafka-2
    ports:
      - "${KAFKA_2_PORT}:9092"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/tmp/kafka_jaas.conf"
      KAFKA_LOG_DIRS: /kafka/data/kafka-2
      KAFKA_ZOOKEEPER: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "SASL_PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://:9092"
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
    volumes:
      - kafka_data:/kafka/data
      - ./docker/kafka/command-auth.properties:/tmp/command-auth.properties
      - ./docker/kafka/kafka_jaas.conf:/tmp/kafka_jaas.conf

  kafka-3:
    profiles:
      - main
    <<: *kafka
    container_name: opium-kafka-3
    ports:
      - "${KAFKA_3_PORT}:9092"
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/tmp/kafka_jaas.conf"
      KAFKA_LOG_DIRS: /kafka/data/kafka-3
      KAFKA_ZOOKEEPER: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: "SASL_PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://:9092"
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
    volumes:
      - kafka_data:/kafka/data
      - ./docker/kafka/command-auth.properties:/tmp/command-auth.properties
      - ./docker/kafka/kafka_jaas.conf:/tmp/kafka_jaas.conf

volumes:
  mysql_data:
  mysql_data_branch:
  redis_data:
    driver: local
  kafka_data:
    driver: local
